name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: arch-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd SPV/ && cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
